### PR TITLE
1.5 updates

### PR DESCRIPTION
**Pull request by qreeves**

### CODE REVIEW

**Comment by stainsby** [comment]
Thanks for this Quin. However, when I test it locally:

$ node ./app.js 
2015-03-22 13:57:27.854 INFO  main:52 - starting web UI on port: 28080
2015-03-22 13:57:27.863 INFO  /home/sam/work/ss_pty_ltd/projects/redflare/poller.js:233 - polling master server
2015-03-22 13:57:28.750 INFO  /home/sam/work/ss_pty_ltd/projects/redflare/poller.js:259 - found servers: 9
2015-03-22 13:57:28.754 INFO  /home/sam/work/ss_pty_ltd/projects/redflare/poller.js:179 - checking status of server: 74.81.175.2028802
2015-03-22 13:57:29.061 INFO  /home/sam/work/ss_pty_ltd/projects/redflare/poller.js:193 -   .. procesing server reply for: 74.81.175.2028802
2015-03-22 13:57:29.064 WARN  /home/sam/work/ss_pty_ltd/projects/redflare/poller.js:199 - server reply processing failed: [ReferenceError: varmaj is not defined]

**Comment by qreeves** [comment]
Sorry, I haven't set up an environment suitable for testing this myself yet.

**Comment by qreeves** [comment]
I pushed a fix for the 'varmaj' typo, does this resolve the issues with this PR? Would be great to get it live ASAP because 1.5 servers are showing up corrupted.

**Comment by stainsby** [comment]
It fixes that, but then only lists the 1.5 servers — and breaks the map names. I'll take a look and see if I can extract the best parts. :-)

**Comment by qreeves** [comment]
I had no idea what I was doing anyway :tongue:

**Comment by stainsby** [comment]
Done and made live. All seems to be working.

**Pull request closed without merging**
